server:
  port: 8080

spring:
  rabbitmq:
    username: admin
    password: admin
    virtual-host: /
    host: 112.124.33.37
    port: 5672

  redis:
    host: 112.124.33.37
    port: 6379
    database: 0



